# -*- coding: utf-8 -*-
"""kmeans_clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xEzMjgJmziaDKVU8ml9G-CBdJxOrbDfj
"""

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
import statsmodels.api as sm

iris = load_iris()
iris_dataset = sm.datasets.get_rdataset("iris")
iris = iris_dataset.data
iris.Species = iris.Species.astype("category")

iris.drop('Species', axis=1)

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans

X = iris.drop('Species', axis=1)
y = iris['Species']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, shuffle=True)
kmeans = KMeans(n_clusters=4, init='k-means++', random_state=42, n_init='auto')
kmeans.fit(X_train)
y_pred = kmeans.predict(X_test)

centers = kmeans.cluster_centers_
labels = kmeans.labels_

X_train_values = X_train.values
#get difference of error
errors = []

for i in range(len(X_train_values)):
  center = centers[labels[i]]
  eucl_dist = np.linalg.norm(X_train_values[i] - center) ** 2
  errors.append(eucl_dist)


rmse = np.sqrt(np.mean(errors))
print("RMSE=", rmse)