# -*- coding: utf-8 -*-
"""perceptron_classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r7rkh_huXsZRODCfacEmaWq-ZCp1LEkB
"""

import pandas as pd
import numpy as np
import statsmodels.api as sm
import matplotlib.pyplot as plt
from patsy import dmatrices
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, cross_val_score, KFold

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
iris = load_iris()
iris_dataset = sm.datasets.get_rdataset("iris")
iris = iris_dataset.data
iris.Species = iris.Species.astype("category")

iris

x1 = iris.drop('Species', axis=1)
y1 = iris['Species']

binary = ['setosa', 'versicolor']
indices = y1.isin(binary)
y1 = y1[indices]
y1 = y1.map({'setosa': 0, 'versicolor': 1})
x1 = x1[indices]

x_train, x_test, y_train, y_test = train_test_split(x1, y1, test_size=0.2, random_state=42)

class Perceptron:
  def __init__(self, learning_rate=0.01, n_iters=1000):
        self.lr = learning_rate
        self.n_iters = n_iters
        self.weights = None
        self.bias = None

  def activation(self, x):
        return np.where(x >= 0, 1, 0)

  def fit(self, X, y):
        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        self.bias = 0

        for _ in range(self.n_iters):
            for i, x in enumerate(X.values):
                linear_output = np.dot(x, self.weights) + self.bias
                y_predicted = self.activation(linear_output)
                update = self.lr * (y.iloc[i] - y_predicted)
                self.weights += update * x
                self.bias += update

  def predict(self, X):
        linear_output = np.dot(X, self.weights) + self.bias
        return self.activation(linear_output)



perceptron = Perceptron(learning_rate=0.01, n_iters=1000)
perceptron.fit(x_train, y_train)

y_pred = perceptron.predict(x_test)
accuracy  = accuracy_score(y_test, y_pred)
print("Perceptron Accuracy: ", accuracy)
